### ISSUE TITLE
The default main page wiki node should not be stored in config at all but only in state as it's environment-specific

### ISSUE THREAD

**Issue by Ambient-Impact** [neurocracy/omnipedia#35]
The primary motivation for this is to avoid the risk of overwriting a different front page set on the production site via a config import.

We can implement our own controller which is set as the default front page, which then redirects to the default main page or the current date's main page, if a session contains one.

This would also allow us to avoid the issue where Drupal core (or the [Redirect module](https://www.drupal.org/project/redirect)?) removes the path for the front page and redirects to `/`.

- [x] neurocracy/drupal-omnipedia-core#16
- [x] neurocracy/drupal-omnipedia-core#17
- [x] neurocracy/drupal-omnipedia-date#7
- [x] Add a main page route and controller (`/wiki/Main_Page`); see [neurocracy/drupal-omnipedia-main-page](https://github.com/neurocracy/drupal-omnipedia-main-page)
- [x] Set new route as front page config
- [x] neurocracy/drupal-omnipedia-date#6
- [x] neurocracy/drupal-omnipedia-main-page#2
- [x] neurocracy/drupal-omnipedia-main-page#1
- [x] neurocracy/drupal-omnipedia-date#10
- [x] neurocracy/drupal-omnipedia-main-page#4
- [x] neurocracy/drupal-omnipedia-main-page#5

# See also

The [System Page Override module](https://www.drupal.org/project/system_page_override) could handle this for us but a custom implementation would be preferred because it gives us more control of how it works.
